language: r
cache: packages
pandoc_version: 2.7.3

script:
  - Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  target_branch: master
  local_dir: _book
  on:
    branch: devel
